version: '3'

networks:
  jaeger-el:
    driver: bridge

services:

    jaeger-collector:
      image: jaegertracing/jaeger-collector:1.34
      restart: on-failure
      command: [ "--collector.zipkin.host-port=9411", "--collector.queue-size=2500", "--collector.num-workers=75", "--es.server-urls=http://elasticsearch-storage:9200" , "--es-archive.num-replicas=1" , "--es-archive.num-shards=5"]
      ports:
        - "14269:14269"
        - "9411:9411"
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
        - LOG_LEVEL=debug
      depends_on:
        - elasticsearch-storage
      networks:
        - jaeger-el
    jaeger-query:
      image: jaegertracing/jaeger-query:1.34
      restart: on-failure
      command: ["--es.server-urls=http://elasticsearch-storage:9200" , "--es-archive.num-replicas=1" , "--es-archive.num-shards=5"]
      ports:
        - "16686:16686"
        - "16687:16687"
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
      depends_on:
        - elasticsearch-storage
      networks:
        - jaeger-el

    elasticsearch-storage:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
      restart: on-failure
      environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
       - "9200:9200"
       - "9300:9300"
      networks:
        - jaeger-el
      volumes:
        - es-data:/usr/share/elasticsearch/data

    elasticsearch_exporter:
      image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.3.0
      command:
        - '--es.uri=http:/elasticsearch-storage:9200'
      restart: always
      depends_on:
        - elasticsearch-storage
      ports:
        - "9114:9114"

    jaeger-es-index-cleaner:
      image: jaegertracing/jaeger-es-index-cleaner:1.34
      command:
        - "7"
        - "http://elasticsearch-storage:9200"
      networks:
        - jaeger-el

    kibana:
      image: docker.elastic.co/kibana/kibana-oss:7.7.1
      restart: on-failure
      ports:
        - "5601:5601"
      environment:
        SERVER_NAME: "kibana"
        ELASTICSEARCH_HOSTS: "http://elasticsearch-storage:9200"
      depends_on:
        - elasticsearch-storage
      networks:
        - jaeger-el
    
volumes:
  es-data:
    driver: local