version: "3.3"

volumes:
  grafana_data:
  prometheus_data:

networks:
  monitor-system:

services:
  prometheus:
    image: prom/prometheus:v2.33.1
    ports:
      - "9090:9090"
    networks:
      - monitor-system
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.0.2
    networks:
      - monitor-system
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    volumes:
        - grafana_data:/var/lib/grafana
