version: "3.3"

volumes:
  grafana_data:
  prometheus_data:

networks:
  monitor-system:

services:
  prometheus:
    image: prom/prometheus:v2.33.1
    ports:
      - "9090:9090"
    networks:
      - monitor-system
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.0.2
    networks:
      - monitor-system
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"

  alertmanager:
    image: prom/alertmanager:v0.23.0
    networks:
      - monitor-system
    depends_on:
      - prometheus
    ports: 
      - "9093:9093"
    volumes:      
      - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
